### ISSUE TITLE
First two links in README don't appear to be correct

### ISSUE THREAD

**Issue by jimoquinn** [gnieser/quasar-keycloak#1]
I'm receiving 404 errors on the first two links in the README.

Specifically these two:

```
Download: [https://www.keycloak.org/getting-started](https://github.com/gnieser/quasar-keycloak/blob/master)

Create a realm, a user and a client: [https://www.keycloak.org/getting-started/getting-started-zip](https://github.com/gnieser/quasar-keycloak/blob/master)
```
I'd create a PR, but unclear where the first link is supposed to go because both URLs generate a 404.  I believe the 2nd link is intended to download keycloak, but the verbiage doesn't match so not exactly sure what you're going for.

**Comment by gnieser** [comment]
Please note that the bug this reproducer aims at demonstrating is not rooted in Quasar but in Vue (router), see: https://github.com/gnieser/vue-keycloak
